name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل المشروع
        uses: actions/checkout@v4

      - name: تثبيت Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: تثبيت Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: تثبيت dependencies
        run: npm install
        working-directory: ./healthsphere-app

      - name: بناء المشروع
        run: npm run build
        working-directory: ./healthsphere-app

      - name: Capacitor sync
        run: npx cap sync
        working-directory: ./healthsphere-app

      - name: بناء APK
        run: |
          cd healthsphere-app/android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: رفع APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: healthsphere-app/android/app/build/outputs/apk/debug/app-debug.apk
